project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: "ml_knot_theory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



